import {
  readdirSync,
  readFileSync,
  writeFileSync,
  statSync,
} from "node:fs";
import { join, basename, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { toYaml } from "./yaml.js";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const specsDir = join(__dirname, "..", "specs");

interface SpecEntry {
  category: string;
  slug: string;
  relPath: string; // e.g. "ip-intelligence/ip-locator.json"
}

function walkSpecs(dir: string, category?: string): SpecEntry[] {
  const entries: SpecEntry[] = [];
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      entries.push(...walkSpecs(full, name));
    } else if (name.endsWith(".json")) {
      const slug = basename(name, ".json");
      const relPath = relative(specsDir, full).replace(/\\/g, "/");
      entries.push({ category: category ?? "uncategorized", slug, relPath });
    }
  }
  return entries;
}

const specs = walkSpecs(specsDir);

function toConstKey(value: string): string {
  const key = value
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase();
  return /^[0-9]/.test(key) ? `_${key}` : key;
}

function buildEnumMap(values: string[]): Map<string, string> {
  const map = new Map<string, string>();
  for (const value of values) {
    const key = toConstKey(value);
    const existing = map.get(key);
    if (existing !== undefined && existing !== value) {
      throw new Error(
        `Const key collision: '${key}' maps to both '${existing}' and '${value}'`,
      );
    }
    map.set(key, value);
  }
  return map;
}

const imports = specs.map((s, i) => {
  return `import _s${i} from '../specs/${s.relPath}' with { type: 'json' };`;
});

const specEntries = specs.map((s, i) => {
  return `  '${s.slug}': _s${i} as OpenAPISpec,`;
});

const slugs = specs.map((s) => `'${s.slug}'`);

const yamlEntries = specs.map((s) => {
  const parsed = JSON.parse(
    readFileSync(join(specsDir, s.relPath), "utf-8"),
  );
  return `  '${s.slug}': ${JSON.stringify(toYaml(parsed))},`;
});

const categories = [...new Set(specs.map((s) => s.category))].sort();

const categoryEntries = categories.map((cat) => {
  const catSlugs = specs
    .filter((s) => s.category === cat)
    .map((s) => `'${s.slug}'`);
  return `  '${cat}': [${catSlugs.join(", ")}],`;
});

const slugEnumMap = buildEnumMap(specs.map((s) => s.slug));
const slugEnumEntries = [...slugEnumMap.entries()]
  .sort(([, a], [, b]) => a.localeCompare(b))
  .map(([key, value]) => `  ${key}: '${value}',`);

const categoryEnumMap = buildEnumMap(categories);
const categoryEnumEntries = [...categoryEnumMap.entries()]
  .sort(([, a], [, b]) => a.localeCompare(b))
  .map(([key, value]) => `  ${key}: '${value}',`);

const content = `// AUTO-GENERATED by scripts/generate-manifest.ts — do not edit manually
import type { OpenAPISpec } from './types.js';

${imports.join("\n")}

export const SPECS: Record<string, OpenAPISpec> = {
${specEntries.join("\n")}
};

export const SPEC_SLUGS: string[] = [${slugs.join(", ")}];

/**
 * YAML text for each spec, pre-rendered at build time so consumers never
 * pay a runtime YAML-dump cost.
 */
export const SPECS_YAML: Record<string, string> = {
${yamlEntries.join("\n")}
};

export const SPEC_CATEGORIES: string[] = [${categories.map((c) => `'${c}'`).join(", ")}];

export const SPECS_BY_CATEGORY: Record<string, string[]> = {
${categoryEntries.join("\n")}
};

/**
 * Enumerated spec slugs. Import and reference these instead of raw strings —
 * if a spec file is renamed or removed, the corresponding key disappears here
 * and every usage in a host app fails to compile instead of failing silently at runtime.
 */
export const SpecSlug = {
${slugEnumEntries.join("\n")}
} as const;

export type SpecSlugValue = (typeof SpecSlug)[keyof typeof SpecSlug];

/**
 * Enumerated spec categories, same rename-safety guarantee as SpecSlug.
 */
export const SpecCategory = {
${categoryEnumEntries.join("\n")}
} as const;

export type SpecCategoryValue = (typeof SpecCategory)[keyof typeof SpecCategory];
`;

const outPath = join(__dirname, "..", "src", "manifest.ts");
writeFileSync(outPath, content, "utf-8");
console.log(
  `Generated manifest with ${specs.length} specs across ${categories.length} categories`,
);
